
export const VERSION="v1.0.0";

export const PRIMARY=[
{name:"Bear",icon:"🐻",archetype:"Juggernaut",stats:{hp:150,atk:116,def:119,spd:67},moves:["Maul","Crushing Swipe","Hibernating Guard","Roar"]},
{name:"Wolf",icon:"🐺",archetype:"Hunter",stats:{hp:106,atk:111,def:82,spd:119},moves:["Fang Rush","Pack Lunge","Hamstring","Howl"]},
{name:"Shark",icon:"🦈",archetype:"Executioner",stats:{hp:128,atk:126,def:87,spd:91},moves:["Savage Bite","Blood Scent","Tail Crash","Feeding Frenzy"]},
{name:"Tiger",icon:"🐯",archetype:"Striker",stats:{hp:113,atk:129,def:79,spd:116},moves:["Rending Claw","Pounce","Ambush","Predator Stance"]},
{name:"Gorilla",icon:"🦍",archetype:"Brawler",stats:{hp:139,atk:127,def:103,spd:74},moves:["Hammer Fist","Ground Pound","Chest Beat","Grapple"]},
{name:"Rhino",icon:"🦏",archetype:"Bulwark",stats:{hp:152,atk:117,def:133,spd:57},moves:["Gore","Stampede","Iron Charge","Brace"]},
{name:"Crocodile",icon:"🐊",archetype:"Grappler",stats:{hp:143,atk:122,def:117,spd:62},moves:["Death Roll","Jaw Lock","Tail Sweep","River Lurk"]},
{name:"Lion",icon:"🦁",archetype:"Commander",stats:{hp:122,atk:125,def:92,spd:103},moves:["King's Claw","Royal Roar","Pride Strike","Dominance"]},
{name:"Elephant",icon:"🐘",archetype:"Colossus",stats:{hp:167,atk:112,def:137,spd:48},moves:["Tusk Lift","Trample","Earthshaker","Fortify"]},
{name:"Hippo",icon:"🦛",archetype:"Crusher",stats:{hp:159,atk:119,def:130,spd:52},moves:["Jaw Crush","Body Slam","Mud Guard","Rage"]},
{name:"Panther",icon:"🐆",archetype:"Assassin",stats:{hp:104,atk:123,def:73,spd:130},moves:["Shadow Pounce","Silent Claw","Vanish","Neck Bite"]},
{name:"Boar",icon:"🐗",archetype:"Berserker",stats:{hp:133,atk:114,def:102,spd:79},moves:["Tusk Rush","Wild Swing","Refuse Death","Fury"]},
{name:"Bison",icon:"🦬",archetype:"Vanguard",stats:{hp:150,atk:118,def:119,spd:63},moves:["Stampede","Horn Toss","Stand Ground","Momentum Crash"]},
{name:"Komodo",icon:"🦎",archetype:"Attrition",stats:{hp:119,atk:114,def:93,spd:89},moves:["Rotting Bite","Heavy Tail","Patient Hunt","Toxic Saliva"]},
{name:"Hyena",icon:"🐕",archetype:"Opportunist",stats:{hp:112,atk:115,def:81,spd:111},moves:["Cackle Bite","Cheap Shot","Scavenge","Pack Rush"]},
{name:"Moose",icon:"🫎",archetype:"Bruiser",stats:{hp:138,atk:113,def:105,spd:82},moves:["Antler Slam","Hoof Crush","Territorial","Charge"]},
{name:"Orca",icon:"🐋",archetype:"Apex",stats:{hp:148,atk:129,def:100,spd:83},moves:["Apex Bite","Wave Crash","Echolocation","Breach"]},
{name:"Cobra",icon:"🐍",archetype:"Duelist",stats:{hp:92,atk:119,def:62,spd:133},moves:["Venom Fang","Coil","Hypnotic Sway","Quick Strike"]},
{name:"Eagle",icon:"🦅",archetype:"Skirmisher",stats:{hp:97,atk:117,def:70,spd:138},moves:["Dive Attack","Talon Rake","Wing Guard","Sky Hunt"]},
{name:"Ram",icon:"🐏",archetype:"Charger",stats:{hp:127,atk:116,def:109,spd:87},moves:["Headbutt","Ram Rush","Thick Skull","Rebound"]},
{name:"Jaguar",icon:"🐆",archetype:"Predator",stats:{hp:109,atk:127,def:77,spd:125},moves:["Jungle Pounce","Spotted Fury","Throat Bite","Stalk"]},
{name:"Walrus",icon:"🦭",archetype:"Tank",stats:{hp:154,atk:107,def:126,spd:54},moves:["Tusk Bash","Blubber Guard","Belly Crush","Cold Blood"]},
{name:"Kangaroo",icon:"🦘",archetype:"Combo",stats:{hp:117,atk:115,def:79,spd:122},moves:["Double Kick","Tail Balance","Bounding Jab","Counter Kick"]},
{name:"Buffalo",icon:"🐃",archetype:"Vanguard",stats:{hp:147,atk:121,def:116,spd:66},moves:["Horn Drive","Dust Charge","Herd Guard","Stomp"]},
{name:"Polar Bear",icon:"🐻‍❄️",archetype:"Juggernaut",stats:{hp:155,atk:118,def:124,spd:61},moves:["Frost Maul","Ice Guard","Whiteout","Crushing Paw"]}
];

export const SECONDARY=[
{name:"Rabbit",icon:"🐇",trait:"Quick-footed",stats:{hp:0,atk:2,def:-2,spd:20},move:"Rapid Kick"},
{name:"Owl",icon:"🦉",trait:"Watchful",stats:{hp:-2,atk:7,def:2,spd:8},move:"Night Sight"},
{name:"Gopher",icon:"🐹",trait:"Burrowing",stats:{hp:7,atk:0,def:7,spd:1},move:"Burrow Rush"},
{name:"Crow",icon:"🐦‍⬛",trait:"Cunning",stats:{hp:-1,atk:5,def:0,spd:10},move:"Eye Peck"},
{name:"Scorpion",icon:"🦂",trait:"Venomous",stats:{hp:0,atk:12,def:4,spd:-2},move:"Stinger"},
{name:"Porcupine",icon:"🦔",trait:"Spined",stats:{hp:5,atk:3,def:12,spd:-5},move:"Quill Burst"},
{name:"Bat",icon:"🦇",trait:"Echolocating",stats:{hp:-4,atk:3,def:-2,spd:15},move:"Sonic Screech"},
{name:"Frog",icon:"🐸",trait:"Springy",stats:{hp:3,atk:2,def:3,spd:8},move:"Tongue Snap"},
{name:"Mantis",icon:"🦗",trait:"Bladed",stats:{hp:-3,atk:11,def:-3,spd:11},move:"Scythe Cut"},
{name:"Turtle",icon:"🐢",trait:"Shelled",stats:{hp:10,atk:-3,def:16,spd:-12},move:"Shell Brace"},
{name:"Rat",icon:"🐀",trait:"Resourceful",stats:{hp:2,atk:5,def:0,spd:9},move:"Filthy Bite"},
{name:"Fox",icon:"🦊",trait:"Elusive",stats:{hp:0,atk:4,def:1,spd:12},move:"Feint"},
{name:"Hawk",icon:"🦅",trait:"Razor-eyed",stats:{hp:-2,atk:9,def:0,spd:10},move:"Talon Dive"},
{name:"Badger",icon:"🦡",trait:"Tenacious",stats:{hp:8,atk:7,def:8,spd:-2},move:"Dig In"},
{name:"Lizard",icon:"🦎",trait:"Regrowing",stats:{hp:1,atk:4,def:4,spd:7},move:"Tail Shed"},
{name:"Snake",icon:"🐍",trait:"Coiling",stats:{hp:-2,atk:8,def:-2,spd:13},move:"Constrict"},
{name:"Raccoon",icon:"🦝",trait:"Tricky",stats:{hp:3,atk:3,def:3,spd:6},move:"Pocket Sand"},
{name:"Squirrel",icon:"🐿️",trait:"Restless",stats:{hp:-1,atk:1,def:0,spd:16},move:"Acorn Barrage"},
{name:"Crab",icon:"🦀",trait:"Armored",stats:{hp:5,atk:2,def:13,spd:-8},move:"Pincer Lock"},
{name:"Hummingbird",icon:"🐦",trait:"Hyperfast",stats:{hp:-5,atk:0,def:-5,spd:23},move:"Needle Rush"},
{name:"Mole",icon:"🐹",trait:"Grounded",stats:{hp:8,atk:4,def:9,spd:-4},move:"Tunnel Strike"},
{name:"Bee",icon:"🐝",trait:"Stinging",stats:{hp:-3,atk:7,def:-3,spd:14},move:"Swarm Sting"},
{name:"Chameleon",icon:"🦎",trait:"Camouflaged",stats:{hp:0,atk:2,def:6,spd:7},move:"Fade"},
{name:"Skunk",icon:"🦨",trait:"Noxious",stats:{hp:4,atk:3,def:4,spd:2},move:"Musk Cloud"},
{name:"Falcon",icon:"🦅",trait:"Diving",stats:{hp:-3,atk:8,def:-1,spd:14},move:"Meteor Dive"}
];

export const ABILITIES=[
{name:"Flaming Blood",icon:"🔥",rarity:"Uncommon",desc:"Attackers are burned when they deal direct damage.",effect:"retaliateBurn"},
{name:"Venom Glands",icon:"☠️",rarity:"Common",desc:"Direct attacks have a 28% chance to poison.",effect:"attackPoison"},
{name:"Glass Cannon",icon:"💥",rarity:"Rare",desc:"+32% ATK and -24% DEF.",mods:{atk:1.32,def:.76}},
{name:"Iron Hide",icon:"🛡️",rarity:"Common",desc:"+25% DEF and -8% SPD.",mods:{def:1.25,spd:.92}},
{name:"Adrenal Surge",icon:"⚡",rarity:"Uncommon",desc:"Below 40% HP, gain 38% SPD.",effect:"lowHpSpeed"},
{name:"Regenerator",icon:"🧬",rarity:"Rare",desc:"Heal 6% max HP after every action.",effect:"regen"},
{name:"Berserker",icon:"🩸",rarity:"Rare",desc:"Gain up to 60% damage as HP falls.",effect:"berserk"},
{name:"Second Heart",icon:"❤️‍🔥",rarity:"Legendary",desc:"Revive once at 28% HP.",effect:"revive"},
{name:"Thorned",icon:"🦔",rarity:"Uncommon",desc:"Reflect 20% direct damage.",effect:"reflect"},
{name:"Predator Focus",icon:"👁️",rarity:"Common",desc:"Deal 24% more damage to targets below half HP.",effect:"execute"},
{name:"Momentum",icon:"🏃",rarity:"Uncommon",desc:"Each action grants 7% SPD, up to 35%.",effect:"momentum"},
{name:"Vampiric Bite",icon:"🧛",rarity:"Rare",desc:"Heal for 18% of direct damage dealt.",effect:"lifesteal"},
{name:"Toxic Skin",icon:"🧪",rarity:"Uncommon",desc:"Attackers have a 35% chance to be poisoned.",effect:"retaliatePoison"},
{name:"Unstable Core",icon:"☢️",rarity:"Rare",desc:"+20% damage, but lose 3% max HP after acting.",effect:"unstable"},
{name:"Pack Hunter",icon:"🐾",rarity:"Common",desc:"+11% damage for each living ally.",effect:"pack"},
{name:"Stonewall",icon:"🧱",rarity:"Uncommon",desc:"The first hit taken deals 60% less damage.",effect:"firstGuard"},
{name:"Quick Reflexes",icon:"💨",rarity:"Rare",desc:"19% chance to evade direct attacks.",effect:"evade"},
{name:"Critical Mass",icon:"🎯",rarity:"Rare",desc:"20% chance to deal 175% damage.",effect:"crit"},
{name:"Counterstrike",icon:"↩️",rarity:"Rare",desc:"22% chance to counter after direct damage.",effect:"counter"},
{name:"Frenzy",icon:"🌀",rarity:"Uncommon",desc:"A knockout fills 50% of the action gauge.",effect:"frenzy"},
{name:"Last Stand",icon:"🗿",rarity:"Rare",desc:"The first lethal hit leaves this mutant at 1 HP.",effect:"lastStand"},
{name:"Blood Price",icon:"🩸",rarity:"Rare",desc:"+42% ATK, but every attack costs 6% max HP.",mods:{atk:1.42},effect:"bloodPrice"},
{name:"Static Coat",icon:"⚡",rarity:"Uncommon",desc:"Attackers have a 30% chance to be slowed.",effect:"retaliateSlow"},
{name:"Phase Skin",icon:"🌫️",rarity:"Legendary",desc:"The first two direct attacks have a 45% miss chance.",effect:"phase"},
{name:"Heavyweight",icon:"🏋️",rarity:"Common",desc:"+18% HP and +12% damage, -16% SPD.",mods:{hp:1.18,spd:.84},effect:"heavyDamage"},
{name:"Overclocked",icon:"⏱️",rarity:"Rare",desc:"+30% SPD, but take 12% more damage.",mods:{spd:1.30},effect:"fragile"},
{name:"Battle Trance",icon:"🧠",rarity:"Uncommon",desc:"Every third action deals 45% more damage.",effect:"trance"},
{name:"Execution Protocol",icon:"⚔️",rarity:"Legendary",desc:"Knock out enemies below 12% HP after direct damage.",effect:"execution"},
{name:"Mirrored Nerves",icon:"🪞",rarity:"Rare",desc:"Copy 20% of each positive speed gain from enemies.",effect:"mirrorSpeed"},
{name:"Rot Cloud",icon:"🦠",rarity:"Uncommon",desc:"All enemies begin battle with one poison stack.",effect:"openingPoison"},
{name:"Arena Favorite",icon:"👑",rarity:"Common",desc:"Gain 8% to all stats while outnumbered.",effect:"underdog"},
{name:"Predatory Healing",icon:"🫀",rarity:"Rare",desc:"Heal 22% max HP after scoring a knockout.",effect:"koHeal"},
{name:"Crushing Presence",icon:"🧿",rarity:"Uncommon",desc:"Enemies begin with 12% less action gauge.",effect:"gaugeSuppress"},
{name:"Reactive Armor",icon:"🔩",rarity:"Rare",desc:"Gain 8% DEF after each hit, up to 32%.",effect:"reactiveDef"},
{name:"Razor Tempo",icon:"🗡️",rarity:"Rare",desc:"Quick moves deal 25% more damage.",effect:"quickPower"},
{name:"Deep Reservoir",icon:"🌊",rarity:"Common",desc:"+22% HP.",mods:{hp:1.22}},
{name:"Perfect Balance",icon:"☯️",rarity:"Legendary",desc:"+10% to all four stats.",mods:{hp:1.10,atk:1.10,def:1.10,spd:1.10}},
{name:"Doom Clock",icon:"⌛",rarity:"Legendary",desc:"Gain 10% damage each round of personal actions.",effect:"doom"},
{name:"Parasite",icon:"🪱",rarity:"Rare",desc:"Steal 4 SPD from the target after each direct hit.",effect:"stealSpeed"},
{name:"Cold Start",icon:"❄️",rarity:"Uncommon",desc:"Take 25% less damage until this mutant acts.",effect:"coldStart"}
];

export const MOVE_LIBRARY={
"Maul":{power:45,recovery:105,tags:["physical"],effect:"bleed",chance:.25},
"Crushing Swipe":{power:39,recovery:91,tags:["physical"]},
"Hibernating Guard":{power:0,recovery:66,tags:["guard"],effect:"guard"},
"Roar":{power:0,recovery:78,tags:["utility"],effect:"weakenAll"},
"Fang Rush":{power:34,recovery:72,tags:["physical","quick"]},
"Pack Lunge":{power:40,recovery:92,tags:["physical"],effect:"allyScale"},
"Hamstring":{power:27,recovery:76,tags:["physical","quick"],effect:"slow",chance:.8},
"Howl":{power:0,recovery:82,tags:["utility"],effect:"buffAttack"},
"Savage Bite":{power:44,recovery:98,tags:["physical"],effect:"bleed",chance:.35},
"Blood Scent":{power:25,recovery:66,tags:["physical","quick"],effect:"woundedBonus"},
"Tail Crash":{power:37,recovery:88,tags:["physical"],effect:"slow",chance:.3},
"Feeding Frenzy":{power:32,recovery:74,tags:["physical","quick"],effect:"lifestealMove"},
"Rending Claw":{power:39,recovery:82,tags:["physical","quick"],effect:"bleed",chance:.3},
"Pounce":{power:36,recovery:76,tags:["physical","quick"],effect:"priority"},
"Ambush":{power:52,recovery:123,tags:["physical"],effect:"firstActionBonus"},
"Predator Stance":{power:0,recovery:70,tags:["utility"],effect:"buffCrit"},
"Hammer Fist":{power:45,recovery:98,tags:["physical"]},
"Ground Pound":{power:31,recovery:108,tags:["physical","area"],effect:"area"},
"Chest Beat":{power:0,recovery:74,tags:["utility"],effect:"buffAttackDef"},
"Grapple":{power:30,recovery:94,tags:["physical"],effect:"stun",chance:.22},
"Gore":{power:46,recovery:104,tags:["physical"],effect:"armorPierce"},
"Stampede":{power:41,recovery:112,tags:["physical","area"],effect:"area"},
"Iron Charge":{power:38,recovery:96,tags:["physical"],effect:"defScale"},
"Brace":{power:0,recovery:62,tags:["guard"],effect:"guardStrong"},
"Death Roll":{power:50,recovery:118,tags:["physical"],effect:"bleed",chance:.55},
"Jaw Lock":{power:34,recovery:91,tags:["physical"],effect:"weaken",chance:.65},
"Tail Sweep":{power:32,recovery:84,tags:["physical","area"],effect:"areaLow"},
"River Lurk":{power:0,recovery:69,tags:["utility"],effect:"evasionBuff"},
"King's Claw":{power:42,recovery:90,tags:["physical"]},
"Royal Roar":{power:0,recovery:82,tags:["utility"],effect:"buffTeamAttack"},
"Pride Strike":{power:35,recovery:77,tags:["physical","quick"],effect:"allyScale"},
"Dominance":{power:30,recovery:86,tags:["physical"],effect:"weaken"},
"Tusk Lift":{power:46,recovery:109,tags:["physical"],effect:"stun",chance:.18},
"Trample":{power:42,recovery:116,tags:["physical","area"],effect:"area"},
"Earthshaker":{power:35,recovery:125,tags:["physical","area"],effect:"slowAll"},
"Fortify":{power:0,recovery:71,tags:["guard"],effect:"fortify"},
"Jaw Crush":{power:48,recovery:112,tags:["physical"],effect:"armorPierce"},
"Body Slam":{power:44,recovery:108,tags:["physical"],effect:"hpScale"},
"Mud Guard":{power:0,recovery:70,tags:["guard"],effect:"guardHeal"},
"Rage":{power:0,recovery:76,tags:["utility"],effect:"buffAttack"},
"Shadow Pounce":{power:40,recovery:74,tags:["physical","quick"],effect:"firstActionBonus"},
"Silent Claw":{power:34,recovery:69,tags:["physical","quick"]},
"Vanish":{power:0,recovery:62,tags:["utility"],effect:"evasionBuff"},
"Neck Bite":{power:49,recovery:111,tags:["physical"],effect:"woundedBonus"},
"Tusk Rush":{power:41,recovery:94,tags:["physical"]},
"Wild Swing":{power:47,recovery:115,tags:["physical"],effect:"wild"},
"Refuse Death":{power:0,recovery:88,tags:["guard"],effect:"lastStandBuff"},
"Fury":{power:0,recovery:72,tags:["utility"],effect:"buffAttack"},
"Horn Toss":{power:43,recovery:102,tags:["physical"],effect:"stun",chance:.16},
"Stand Ground":{power:0,recovery:67,tags:["guard"],effect:"guardStrong"},
"Momentum Crash":{power:37,recovery:93,tags:["physical"],effect:"speedScale"},
"Rotting Bite":{power:35,recovery:91,tags:["physical"],effect:"poison",chance:.65},
"Heavy Tail":{power:40,recovery:99,tags:["physical"]},
"Patient Hunt":{power:0,recovery:72,tags:["utility"],effect:"buffCrit"},
"Toxic Saliva":{power:22,recovery:77,tags:["special","area"],effect:"poisonAll"},
"Cackle Bite":{power:33,recovery:75,tags:["physical","quick"],effect:"woundedBonus"},
"Cheap Shot":{power:29,recovery:67,tags:["physical","quick"],effect:"stun",chance:.1},
"Scavenge":{power:0,recovery:73,tags:["utility"],effect:"selfHeal"},
"Pack Rush":{power:38,recovery:87,tags:["physical"],effect:"allyScale"},
"Antler Slam":{power:43,recovery:101,tags:["physical"]},
"Hoof Crush":{power:39,recovery:94,tags:["physical"],effect:"slow",chance:.45},
"Territorial":{power:0,recovery:70,tags:["guard"],effect:"buffAttackDef"},
"Charge":{power:40,recovery:89,tags:["physical"],effect:"priority"},
"Apex Bite":{power:48,recovery:110,tags:["physical"],effect:"woundedBonus"},
"Wave Crash":{power:37,recovery:105,tags:["physical","area"],effect:"area"},
"Echolocation":{power:0,recovery:64,tags:["utility"],effect:"buffAccuracy"},
"Breach":{power:42,recovery:93,tags:["physical"],effect:"armorPierce"},
"Venom Fang":{power:34,recovery:79,tags:["physical","quick"],effect:"poison",chance:.75},
"Coil":{power:30,recovery:87,tags:["physical"],effect:"slow",chance:.8},
"Hypnotic Sway":{power:0,recovery:77,tags:["utility"],effect:"weaken"},
"Quick Strike":{power:31,recovery:64,tags:["physical","quick"]},
"Dive Attack":{power:40,recovery:77,tags:["physical","quick"],effect:"priority"},
"Talon Rake":{power:35,recovery:73,tags:["physical","quick"],effect:"bleed",chance:.3},
"Wing Guard":{power:0,recovery:65,tags:["guard"],effect:"guard"},
"Sky Hunt":{power:32,recovery:70,tags:["physical","quick"],effect:"woundedBonus"},
"Headbutt":{power:42,recovery:96,tags:["physical"],effect:"stun",chance:.15},
"Ram Rush":{power:39,recovery:88,tags:["physical"],effect:"speedScale"},
"Thick Skull":{power:0,recovery:68,tags:["guard"],effect:"guardStrong"},
"Rebound":{power:32,recovery:75,tags:["physical","quick"],effect:"counterBuff"},
"Jungle Pounce":{power:41,recovery:76,tags:["physical","quick"],effect:"firstActionBonus"},
"Spotted Fury":{power:37,recovery:80,tags:["physical","quick"]},
"Throat Bite":{power:50,recovery:114,tags:["physical"],effect:"executionMove"},
"Stalk":{power:0,recovery:65,tags:["utility"],effect:"buffCrit"},
"Tusk Bash":{power:42,recovery:103,tags:["physical"]},
"Blubber Guard":{power:0,recovery:69,tags:["guard"],effect:"fortify"},
"Belly Crush":{power:45,recovery:111,tags:["physical"],effect:"hpScale"},
"Cold Blood":{power:0,recovery:75,tags:["utility"],effect:"selfHeal"},
"Double Kick":{power:34,recovery:68,tags:["physical","quick"],effect:"doubleHit"},
"Tail Balance":{power:0,recovery:61,tags:["utility"],effect:"evasionBuff"},
"Bounding Jab":{power:29,recovery:61,tags:["physical","quick"]},
"Counter Kick":{power:31,recovery:71,tags:["physical","quick"],effect:"counterBuff"},
"Horn Drive":{power:44,recovery:101,tags:["physical"],effect:"armorPierce"},
"Dust Charge":{power:39,recovery:92,tags:["physical"],effect:"slow",chance:.3},
"Herd Guard":{power:0,recovery:72,tags:["guard"],effect:"teamGuard"},
"Stomp":{power:36,recovery:98,tags:["physical","area"],effect:"areaLow"},
"Frost Maul":{power:44,recovery:104,tags:["physical"],effect:"slow",chance:.5},
"Ice Guard":{power:0,recovery:68,tags:["guard"],effect:"guardStrong"},
"Whiteout":{power:24,recovery:92,tags:["special","area"],effect:"weakenAll"},
"Crushing Paw":{power:47,recovery:110,tags:["physical"]},
"Rapid Kick":{power:28,recovery:58,tags:["physical","quick"],effect:"doubleHitLight"},
"Night Sight":{power:0,recovery:61,tags:["utility"],effect:"buffAccuracyCrit"},
"Burrow Rush":{power:30,recovery:69,tags:["physical","quick"],effect:"priority"},
"Eye Peck":{power:27,recovery:62,tags:["physical","quick"],effect:"weaken",chance:.35},
"Stinger":{power:31,recovery:76,tags:["physical"],effect:"poison",chance:.7},
"Quill Burst":{power:29,recovery:82,tags:["physical","area"],effect:"areaLow"},
"Sonic Screech":{power:22,recovery:72,tags:["special","area"],effect:"weakenAll"},
"Tongue Snap":{power:28,recovery:65,tags:["physical","quick"],effect:"slow",chance:.25},
"Scythe Cut":{power:34,recovery:67,tags:["physical","quick"],effect:"bleed",chance:.35},
"Shell Brace":{power:0,recovery:59,tags:["guard"],effect:"guardStrong"},
"Filthy Bite":{power:28,recovery:64,tags:["physical","quick"],effect:"poison",chance:.3},
"Feint":{power:21,recovery:55,tags:["physical","quick"],effect:"evasionBuff"},
"Talon Dive":{power:34,recovery:66,tags:["physical","quick"],effect:"priority"},
"Dig In":{power:0,recovery:63,tags:["guard"],effect:"buffAttackDef"},
"Tail Shed":{power:0,recovery:58,tags:["utility"],effect:"cleanseHeal"},
"Constrict":{power:29,recovery:78,tags:["physical"],effect:"slow",chance:.65},
"Pocket Sand":{power:20,recovery:58,tags:["utility"],effect:"weaken"},
"Acorn Barrage":{power:25,recovery:57,tags:["physical","quick"],effect:"doubleHitLight"},
"Pincer Lock":{power:31,recovery:80,tags:["physical"],effect:"stun",chance:.16},
"Needle Rush":{power:24,recovery:49,tags:["physical","quick"],effect:"doubleHitLight"},
"Tunnel Strike":{power:32,recovery:72,tags:["physical"],effect:"armorPierce"},
"Swarm Sting":{power:26,recovery:60,tags:["physical","quick"],effect:"poison",chance:.42},
"Fade":{power:0,recovery:56,tags:["utility"],effect:"evasionBuff"},
"Musk Cloud":{power:20,recovery:74,tags:["special","area"],effect:"weakenAll"},
"Meteor Dive":{power:36,recovery:69,tags:["physical","quick"],effect:"priority"}
};

export const TIERS=[
{name:"Qualifier",size:4,teamSize:1,wins:2,scale:.78,credit:25},
{name:"Bronze",size:8,teamSize:2,wins:3,scale:.90,credit:35},
{name:"Silver",size:16,teamSize:3,wins:4,scale:1.00,credit:45},
{name:"Gold",size:32,teamSize:3,wins:5,scale:1.12,credit:60},
{name:"Platinum",size:64,teamSize:3,wins:6,scale:1.24,credit:80},
{name:"Elite",size:128,teamSize:3,wins:7,scale:1.38,credit:110},
{name:"Championship",size:256,teamSize:3,wins:8,scale:1.55,credit:160}
];

export const REROLL_COSTS={primary:150,secondary:100,ability:125};
export const MAX_REROLLS=2;
export const MAX_ROSTER=5;
